#include <iostream>
#include <random>

int main()
{
    std::random_device rd; // used to obtain a seed for the randnumber engine
    std::mt19937 gen(rd()); // standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<double> dis(-1.0, 2.0);
    
    for (int n = 0; n < 10; ++n)
        // use dis to transform the random unsigned int generated by gen into
        // a float between [1,6]
        std::cout << dis(gen) << ' ';
    return 0;
}